version: '3.9'
services:
  backend:
    build: ./smartCartApp
    container_name: smartcart-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/smartcart
    depends_on:
      - mongo

  frontend:
    build: ./smartCartUI
    container_name: smartcart-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend

  mongo:
    image: mongo:7
    container_name: smartcart-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
